# LAB | Ensemble Methods

**Load the data**

In this challenge, we will be working with the same Spaceship Titanic data, like the previous Lab. The data can be found here:

https://raw.githubusercontent.com/data-bootcamp-v4/data/main/spaceship_titanic.csv

Metadata

https://github.com/data-bootcamp-v4/data/blob/main/spaceship_titanic.md

In this Lab, you should try different ensemble methods in order to see if can obtain a better model than before. In order to do a fair comparison, you should perform the same feature scaling, engineering applied in previous Lab.

In [118]:
#Libraries
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import BaggingClassifier
from sklearn.metrics import accuracy_score
from sklearn.metrics import accuracy_score, classification_report
from sklearn.ensemble import RandomForestRegressor, RandomForestClassifier
from sklearn.ensemble import GradientBoostingClassifier
from sklearn.ensemble import AdaBoostClassifier
from sklearn.tree import DecisionTreeClassifier

SEED = 32

In [119]:
spaceship = pd.read_csv("https://raw.githubusercontent.com/data-bootcamp-v4/data/main/spaceship_titanic.csv")
spaceship.head()

,PassengerId,HomePlanet,CryoSleep,Cabin,Destination,Age,VIP,RoomService,FoodCourt,ShoppingMall,Spa,VRDeck,Name,Transported
0,0001_01,Europa,False,B/0/P,TRAPPIST-1e,39.0,False,0.0,0.0,0.0,0.0,0.0,Maham Ofracculy,False
1,0002_01,Earth,False,F/0/S,TRAPPIST-1e,24.0,False,109.0,9.0,25.0,549.0,44.0,Juanna Vines,True
2,0003_01,Europa,False,A/0/S,TRAPPIST-1e,58.0,True,43.0,3576.0,0.0,6715.0,49.0,Altark Susent,False
3,0003_02,Europa,False,A/0/S,TRAPPIST-1e,33.0,False,0.0,1283.0,371.0,3329.0,193.0,Solam Susent,False
4,0004_01,Earth,False,F/1/S,TRAPPIST-1e,16.0,False,303.0,70.0,151.0,565.0,2.0,Willy Santantines,True

In [120]:
spaceship = spaceship.dropna()

In [121]:
spaceship = spaceship.drop(columns = ["PassengerId", "Name"])

In [122]:
spaceship["Cabin"] = spaceship["Cabin"].str[0]

In [123]:
spaceship["Cabin"].unique()

array(['B', 'F', 'A', 'G', 'E', 'C', 'D', 'T'], dtype=object)

Now perform the same as before:
- Feature Scaling
- Feature Selection

In [124]:
categorical_cols = spaceship.select_dtypes(include='object').columns
spaceship_encoded = pd.get_dummies(spaceship, columns=categorical_cols, drop_first=True).astype(int)

In [125]:
X = spaceship_encoded.drop(columns=["Transported"])
y = spaceship_encoded["Transported"]

**Perform Train Test Split**

In [126]:
X_train, X_test, y_train, y_test = train_test_split(
    X, y,
    test_size=0.2,
    random_state=SEED,
    stratify=y)  # Keeps the same proportion of the 3 species in both sets

print(f'X_train shape: {X_train.shape}')
print(f'X_test shape:  {X_test.shape}')

X_train shape: (5284, 19)
X_test shape:  (1322, 19)

**Model Selection** - now you will try to apply different ensemble methods in order to get a better model

- Bagging and Pasting

In [127]:
# 1. Crear modelo
bagg_clf = BaggingClassifier(
    estimator=DecisionTreeClassifier(),
    n_estimators=100,
    bootstrap=True,
    random_state=SEED
)

# 2. Entrenar
bagg_clf.fit(X_train, y_train)

# 3. Predecir
y_pred_train = bagg_clf.predict(X_train)
y_pred_test = bagg_clf.predict(X_test)

# 4. Evaluar
acc_train = accuracy_score(y_train, y_pred_train)
acc_test = accuracy_score(y_test, y_pred_test)

print(f'Accuracy (Train): {acc_train * 100:.2f}%')
print(f'Accuracy (Test): {acc_test * 100:.2f}%')

print()
print('Classification Report (Test):')
print(classification_report(y_test, y_pred_test))

Accuracy (Train): 94.27%
Accuracy (Test): 77.61%

Classification Report (Test):
              precision    recall  f1-score   support

           0       0.75      0.81      0.78       656
           1       0.80      0.74      0.77       666

    accuracy                           0.78      1322
   macro avg       0.78      0.78      0.78      1322
weighted avg       0.78      0.78      0.78      1322

- Random Forests

In [128]:
# 1. Crear modelo
rf_clf = RandomForestClassifier(
    n_estimators=100,
    min_samples_split=5,
    min_samples_leaf=2,
    max_features="sqrt",
    random_state=SEED
)


# 2. Entrenar
rf_clf.fit(X_train, y_train)
print("Model Trained!")

Model Trained!

In [129]:
# 3. Predecir
y_pred_train = rf_clf.predict(X_train)
y_pred_test = rf_clf.predict(X_test)

# 4. Evaluar
acc_train = accuracy_score(y_train, y_pred_train)
acc_test = accuracy_score(y_test, y_pred_test)

print(f'Accuracy (Train): {acc_train * 100:.2f}%')
print(f'Accuracy (Test): {acc_test * 100:.2f}%')

print()
print('Classification Report (Test):')
print(classification_report(y_test, y_pred_test))

Accuracy (Train): 89.76%
Accuracy (Test): 78.67%

Classification Report (Test):
              precision    recall  f1-score   support

           0       0.77      0.81      0.79       656
           1       0.80      0.76      0.78       666

    accuracy                           0.79      1322
   macro avg       0.79      0.79      0.79      1322
weighted avg       0.79      0.79      0.79      1322

- Gradient Boosting

In [130]:
# 1. Crear modelo
gb_clf = GradientBoostingClassifier(
    n_estimators=100,
    learning_rate=0.1,
    max_depth=3,
    random_state=SEED
)
# 2. Entrenar
gb_clf.fit(X_train, y_train)
print("Model Trained!")

Model Trained!

In [131]:
# 3. Predecir
y_pred_train = gb_clf.predict(X_train)
y_pred_test = gb_clf.predict(X_test)

# 4. Evaluar
acc_train = accuracy_score(y_train, y_pred_train)
acc_test = accuracy_score(y_test, y_pred_test)

print(f'Accuracy (Train): {acc_train * 100:.2f}%')
print(f'Accuracy (Test): {acc_test * 100:.2f}%')

print()
print('Classification Report (Test):')
print(classification_report(y_test, y_pred_test))

Accuracy (Train): 81.72%
Accuracy (Test): 79.80%

Classification Report (Test):
              precision    recall  f1-score   support

           0       0.82      0.76      0.79       656
           1       0.78      0.83      0.81       666

    accuracy                           0.80      1322
   macro avg       0.80      0.80      0.80      1322
weighted avg       0.80      0.80      0.80      1322

- Adaptive Boosting

In [132]:
ada_clf = AdaBoostClassifier(
    estimator=DecisionTreeClassifier(max_depth=1),
    n_estimators=100,
    learning_rate=0.5,
    random_state=SEED
)
# 2. Entrenar
ada_clf.fit(X_train, y_train)
print("Model Trained!")

Model Trained!

In [133]:
# 3. Predecir
y_pred_train = ada_clf.predict(X_train)
y_pred_test = ada_clf.predict(X_test)

# 4. Evaluar
acc_train = accuracy_score(y_train, y_pred_train)
acc_test = accuracy_score(y_test, y_pred_test)

print(f'Accuracy (Train): {acc_train * 100:.2f}%')
print(f'Accuracy (Test): {acc_test * 100:.2f}%')

print()
print('Classification Report (Test):')
print(classification_report(y_test, y_pred_test))

Accuracy (Train): 77.06%
Accuracy (Test): 77.38%

Classification Report (Test):
              precision    recall  f1-score   support

           0       0.74      0.84      0.79       656
           1       0.82      0.70      0.76       666

    accuracy                           0.77      1322
   macro avg       0.78      0.77      0.77      1322
weighted avg       0.78      0.77      0.77      1322

Which model is the best and why?

In [138]:
from sklearn.metrics import accuracy_score, recall_score

results = []

models = {
    "Bagging": bagg_clf,
    "Random Forest": rf_clf,
    "Gradient Boosting": gb_clf,
    "AdaBoost": ada_clf
}

for name, model in models.items():
    
    y_pred_train = model.predict(X_train)
    y_pred_test = model.predict(X_test)
    
    train_acc = accuracy_score(y_train, y_pred_train)
    test_acc = accuracy_score(y_test, y_pred_test)
    test_recall = recall_score(y_test, y_pred_test)
    
    results.append({
        "Model": name,
        "Train Accuracy": train_acc * 100,
        "Test Accuracy": test_acc * 100,
        "Test Recall": test_recall * 100,
        "Train-Test Gap": (train_acc - test_acc) * 100
    })

results_df = pd.DataFrame(results).round(2)

results_df

,Model,Train Accuracy,Test Accuracy,Test Recall,Train-Test Gap
0,Bagging,94.27,77.61,73.87,16.66
1,Random Forest,89.76,78.67,76.13,11.09
2,Gradient Boosting,81.72,79.80,83.18,1.92
3,AdaBoost,77.06,77.38,70.42,-0.32

The best model is Gradient Boosting beacuase of the small gap in accuracy having a light overfitting, and a grat recall compared to the other model. It's preferable a slightly bigger gap with a 10% of recallc ompared to Ada boost.